name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install SQLite for Bot
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
      
    - name: Build
      run: cargo build --bin nyasubworker
      
    - name: Upload nyasubworker artifact
      uses: actions/upload-artifact@v3
      with:
        name: nyasubworker
        path: target/debug/nyasubworker
